### ISSUE TITLE
CartItem does not have SkuRefId property

### ISSUE THREAD

**Issue by polishq** [vtex-apps/pixel-app-template#7]
SKU Reference IDs are available in ProductView and OrderPlaced events, but not in any of the Cart events (AddToCart, CartChanged, etc).

**Comment by kaisermann** [comment]
The `referenceId` was just added to the `addToCart` event triggered by the `AddToCardButton` component. However, we're still unable to pass it in the event payload for the minicart/checkout events.

**Comment by polishq** [comment]
@kaisermann Thanks, I was just about to comment about that.

**Comment by kaisermann** [comment]
Found a way to pass it and a bug in the addToCart solution! Will get back to you soon 😁

**Comment by kaisermann** [comment]
Gonna happen! However, the `referenceId` will be passed as a string (which is the correct type) instead of the `{ Key, Value }` object that you can find in the `ProductView` event. Unfortunately, I can't fix the type in these other apps for backward compatibility reasons.

Waiting for:
https://github.com/vtex/checkout-graphql/pull/57
https://github.com/vtex-apps/checkout-resources/pull/41
https://github.com/vtex-apps/minicart/pull/222
